# Generated by Django 5.2.5 on 2026-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='proctoring_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='proctoring_session_id',
            field=models.CharField(blank=True, help_text='WebSocket session ID for proctoring', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='proctoring_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='suspicion_score',
            field=models.FloatField(default=0.0, help_text='Cumulative suspicion score'),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='violation_count',
            field=models.IntegerField(default=0, help_text='Number of flagged violations'),
        ),
    ]
