# Generated by Django 5.2.5 on 2026-08-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentside', '0002_studentexamattempt_proctoring_ended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSessionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_directory', models.CharField(max_length=500)),
                ('calibration_file', models.CharField(blank=True, help_text='Path to eye_calibration.json from calibration phase', max_length=500, null=True)),
                ('heatmap_image', models.CharField(blank=True, help_text='Path to heatmap image (exam session only)', max_length=500, null=True)),
                ('session_log_csvs', models.JSONField(blank=True, default=list, help_text='CSV logs - typically 2: calibration + exam session')),
                ('violation_videos', models.JSONField(blank=True, default=list, help_text='Violation video clips from exam session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_files', to='studentside.studentexamattempt')),
            ],
            options={
                'verbose_name': 'Proctoring Session Files',
                'verbose_name_plural': 'Proctoring Session Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
