# Generated by Django 6.0.5 on 2026-08-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('class_designation', models.CharField(max_length=100)),
                ('timelimit', models.DurationField(help_text='Enter the time limit for the exam (e.g., 1:30:00 for 1 hour 30 minutes).')),
                ('attempt_limit', models.PositiveIntegerField(help_text='Enter the maximum number of attempts allowed for this exam.')),
                ('access_code', models.CharField(help_text='Enter a unique access code for the exam.', max_length=20)),
                ('access_status', models.BooleanField(default=False, help_text='Indicates whether the exam is currently accessible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False'), ('NUM', 'Numerical'), ('IMG', 'Image-based'), ('FIB', 'Fill in the Blanks')], max_length=3)),
                ('choices', models.JSONField(blank=True, help_text='Enter choices as a JSON array for MCQ type questions.', null=True)),
                ('correct_answer_text', models.TextField(blank=True, null=True)),
                ('correct_answer_image', models.ImageField(blank=True, null=True, upload_to='answer_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacherside.exam')),
            ],
        ),
    ]
