# Generated by Django 6.0.5 on 2026-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='access_code',
            field=models.CharField(blank=True, help_text='Enter a unique access code for the exam.', max_length=20, null=True),
        ),
    ]
